### ISSUE TITLE
Add a Recipe Rating filter.

### ISSUE THREAD

**Issue by hvudeshi** [het-patel99/Recipe_Recommender#10]

**Comment by hvudeshi** [comment]
I have completed the code for adding a recipe rating filter. Have a look at the code.

**Comment by hvudeshi** [comment]
![ss_filters](https://user-images.githubusercontent.com/22682878/143720718-aab0b4a3-373e-413d-8f7b-beb119770e88.png)


This is how it looks on the server.

**Comment by hvudeshi** [comment]
I am trying to run the server on AWS.

**Comment by hvudeshi** [comment]
@het-patel99 @sal0ni @kalgeekotak99 @Vineet2311 comment on this.

**Comment by het-patel99** [comment]
It's great, If rating filters are displayed correctly. I guess you can close this issue.

**Comment by hvudeshi** [comment]
It is working fine on AWS too.

**Comment by Vineet2311** [comment]
Restaurants suggested are displaying properly as per the requirements. Everything seems fine.

**Comment by kalgeekotak99** [comment]
Looks fine.

**Comment by hvudeshi** [comment]
All looks good, so I am closing this issue.
