### ISSUE TITLE
Update Travis build passing badge.

### ISSUE THREAD

**Issue by hvudeshi** [het-patel99/Recipe_Recommender#11]

**Comment by het-patel99** [comment]
I have updated the travis, do check that, our build is passing and i guess everything seems fine. @hvudeshi @kalgeekotak99 @Vineet2311 @sal0ni  do check this!!

**Comment by Vineet2311** [comment]
Yes, it is working all fine.

**Comment by sal0ni** [comment]
Yes. Working fine.
