### ISSUE TITLE
Create a Demo Video showing working functionalities.

### ISSUE THREAD

**Issue by hvudeshi** [het-patel99/Recipe_Recommender#15]

**Comment by het-patel99** [comment]
@Vineet2311 have you completed making the demo video showing our improvements?. If yes, kindly add that video in our repo!!

**Comment by het-patel99** [comment]
Also, @hvudeshi @Vineet2311 @sal0ni @kalgeekotak99. We will have a zoom meeting for our project-3 final demonstration which professor has asked!! We can join at 6:30pm today?

**Comment by sal0ni** [comment]
Yes

**Comment by Vineet2311** [comment]
Yes

**Comment by hvudeshi** [comment]
Okay!

**Comment by kalgeekotak99** [comment]
yes
