### ISSUE TITLE
Add test cases for recipe rating filter.

### ISSUE THREAD

**Issue by hvudeshi** [het-patel99/Recipe_Recommender#18]

**Comment by kalgeekotak99** [comment]
I have added test case for recipe rating. Review it.
{
<img width="208" alt="image" src="https://user-images.githubusercontent.com/43135408/143801342-9f834e99-6547-4760-bd4d-36a34c509ccd.png">
}

**Comment by Vineet2311** [comment]
Yeah, the test case seems fine, you can close this issue now.

**Comment by het-patel99** [comment]
Great!! You can close this issue now.
