### ISSUE TITLE
Add test cases for cooking filter.

### ISSUE THREAD

**Issue by hvudeshi** [het-patel99/Recipe_Recommender#19]

**Comment by kalgeekotak99** [comment]
I have added the test case for this filter. @sal0ni Review them
https://github.com/het-patel99/Recipe_Recommender/tree/master/test

**Comment by sal0ni** [comment]
I have reviewed. You can close the issue.

**Comment by het-patel99** [comment]
yes, test cases seems fine. You can close this issue!!
