### ISSUE TITLE
Add vegetarian/vegan filters etc.

### ISSUE THREAD

**Issue by het-patel99** [het-patel99/Recipe_Recommender#2]

**Comment by hvudeshi** [comment]
I have added the python file in the Data folder to incorporate the Vegetarian/Non-Vegetarian/Vegan filter. @het-patel99 verify this once and try to incorporate it in the local server.

**Comment by het-patel99** [comment]
Cool, i will work on that and will update on this!!

**Comment by het-patel99** [comment]
@hvudeshi I have tested that Vegetarian/Non-Vegetarian/Vega filter part, its working fine. I guess we can close this issue.

**Comment by hvudeshi** [comment]
Okay, I will check it on AWS and then we can close the issue.

**Comment by hvudeshi** [comment]
I have checked on AWS and it is running fine. @het-patel99 can I close the issue?
