### ISSUE TITLE
Change Email format

### ISSUE THREAD

**Issue by hvudeshi** [het-patel99/Recipe_Recommender#26]

**Comment by het-patel99** [comment]
I have added the youtube video link to the email for every recipe that user is getting. I have checked in my local, @hvudeshi test this on AWS, and do update me here

**Comment by hvudeshi** [comment]
I have verified that already. Can you attach the screenshot for the Email format?

**Comment by het-patel99** [comment]
![image](
https://user-images.githubusercontent.com/44945317/143953813-1dafbac2-24fa-4b77-8d70-d0bf36069f8c.png
)

Here is the attached screenshot.

**Comment by hvudeshi** [comment]
Seems fine, you can close the issue.

**Comment by het-patel99** [comment]
Noted!!
