### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by het-patel99** [het-patel99/Recipe_Recommender#3]

**Comment by het-patel99** [comment]
Kindly add every updates in README.md file to master branch from everyone's individual branch. If done, do update me here so i can close this issue.

**Comment by Vineet2311** [comment]
I have updated the README.md file in the master branch which has all the changes I made. @het-patel99 Check it one.

**Comment by het-patel99** [comment]
Yes, our README.md file is now complete, I am closing this issue.
