### ISSUE TITLE
Add a youtube video page to suggest videos on how to make the recipe.

### ISSUE THREAD

**Issue by hvudeshi** [het-patel99/Recipe_Recommender#36]

**Comment by hvudeshi** [comment]
I have added the youtube video filter to the frontend. It is also added to the Email format as well. @Vineet2311  have you written test cases for that?

**Comment by sal0ni** [comment]
I've checked the youtube video. looks amazing!

**Comment by kalgeekotak99** [comment]
Looks good.

**Comment by het-patel99** [comment]
@hvudeshi could you attach the screenshot exactly in which part of code have you added this?

**Comment by hvudeshi** [comment]
![image](https://user-images.githubusercontent.com/22682878/143956162-dbc5e302-bd87-4236-96bb-cc7f36269413.png)

**Comment by het-patel99** [comment]
Perfect!! close this issue for now
