### ISSUE TITLE
Change code to add restaurant recommendations

### ISSUE THREAD

**Issue by het-patel99** [het-patel99/Recipe_Recommender#5]

**Comment by hvudeshi** [comment]
I have added the python file and dataset (CSV) to the data folder. @het-patel99 verify it once.

**Comment by hvudeshi** [comment]
@Vineet2311 @kalgeekotak99 @sal0ni  have a look at the database I have created.

**Comment by het-patel99** [comment]
@hvudeshi the python file seems fine. Do we need to add any test cases for that?

**Comment by Vineet2311** [comment]
I saw the database, it includes most of the cuisines as per the preferences, it seems fine.

**Comment by het-patel99** [comment]
I guess this is fine, the functionality is working fine and we have already added variety of cuisines. So adding more and more won't make much difference. This should be fine.
