### ISSUE TITLE
Create additional datasets to recommend restaurant

### ISSUE THREAD

**Issue by het-patel99** [het-patel99/Recipe_Recommender#8]

**Comment by hvudeshi** [comment]
@Vineet2311 let me know as soon as you add the dataset.

**Comment by Vineet2311** [comment]
I have updated the dataset and added it in the Data folder. Please check it and let me know

**Comment by hvudeshi** [comment]
Looks good, @Vineet2311 you can close the issue.

**Comment by Vineet2311** [comment]
Okay, I am closing it.
