### ISSUE TITLE
Dockerize the application

### ISSUE THREAD

**Issue by hvudeshi** [het-patel99/Recipe_Recommender#9]

**Comment by hvudeshi** [comment]
I have added the Dockerfile for backend and frontend in their respective folder and also added docker-compose file to trigger those docker files. @het-patel99 @sal0ni @kalgeekotak99 @Vineet2311 have a look at it.

**Comment by Vineet2311** [comment]
I had a look at it, everything seems fine.

**Comment by hvudeshi** [comment]
As everything looks good, I am closing this issue.
